# Generated by Django 3.1.3 on 2020-12-01 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_auto_20201130_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cuser',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
