# Generated by Django 3.1.3 on 2020-12-01 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_auto_20201130_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cuser',
        ),
        migrations.AddField(
            model_name='service',
            name='cuser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='service', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
