# Generated by Django 3.1.3 on 2020-12-01 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_auto_20201201_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use', to=settings.AUTH_USER_MODEL),
        ),
    ]
