# Generated by Django 3.1.3 on 2020-12-01 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0005_auto_20201201_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cuser',
        ),
        migrations.AddField(
            model_name='service',
            name='cuser',
            field=models.ManyToManyField(related_name='use', to=settings.AUTH_USER_MODEL),
        ),
    ]
