# Generated by Django 3.1.2 on 2020-12-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201215_1945'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
