# Generated by Django 3.1.3 on 2021-01-11 20:15

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_factor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='factor',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
