# Generated by Django 3.1.2 on 2021-01-25 16:35

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20210117_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=userprofile.models.get_upload_logo_path),
        ),
    ]
