# Generated by Django 3.1.3 on 2020-11-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Service',
            field=models.ManyToManyField(to='service.Service'),
        ),
    ]
