# Generated by Django 3.1.3 on 2021-01-11 20:22

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
