# Generated by Django 3.1.2 on 2021-01-17 14:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210111_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='description',
        ),
        migrations.AddField(
            model_name='cuser',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, null=True, upload_to=userprofile.models.get_upload_path)),
                ('file2', models.FileField(blank=True, null=True, upload_to=userprofile.models.get_upload_path)),
                ('file3', models.FileField(blank=True, null=True, upload_to=userprofile.models.get_upload_path)),
                ('file4', models.FileField(blank=True, null=True, upload_to=userprofile.models.get_upload_path)),
                ('file5', models.FileField(blank=True, null=True, upload_to=userprofile.models.get_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
