# Generated by Django 3.1.3 on 2021-01-11 19:24

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20201215_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
