# Generated by Django 3.1.3 on 2021-01-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201215_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, default='service_defult.png', null=True, upload_to='logo/'),
        ),
    ]
