# Generated by Django 3.1.3 on 2020-12-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_auto_20201217_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
