# Generated by Django 3.1.3 on 2020-11-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cuser',
            managers=[
            ],
        ),
    ]
