# Generated by Django 3.1.3 on 2020-11-30 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20201130_2238'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cuser',
            managers=[
            ],
        ),
    ]
