# Generated by Django 3.1.3 on 2020-11-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20201130_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='user_type',
            field=models.CharField(choices=[('B', 'کاربر'), ('S', 'استارتاپ'), ('P', 'خدمات دهنده'), ('A', 'مرکز معرفی')], default='B', max_length=1),
        ),
    ]
