# Generated by Django 3.1.3 on 2020-11-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20201130_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email address'),
        ),
    ]
