# Generated by Django 3.1.3 on 2020-12-04 12:21

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20201130_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=userprofile.models.get_upload_path),
        ),
    ]
