# Generated by Django 3.1.3 on 2021-01-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
